// ── APPLICATION STATE (Mock Data) ──────────────────────────────
var S = {

// ── LEADS ──────────────────────────────────────────────────────
leads: [
  {id:'L1',name:'أحمد خالد العنزي',phone:'0501234567',email:'ahmed@gmail.com',
   source:'موقع إلكتروني',stage:'تأهيل',status:'ساخن',score:88,
   assignedTo:'U3',branchId:'B1',teamId:'T1',createdAt:'2026-05-10',lastActivity:'2026-06-08',
   req:{budgetMin:700000,budgetMax:1000000,types:['شقة'],areas:['النرجس','الملقا'],bedrooms:[3]},
   notes:'مهتم بشقة في الرياض. يفضل طابق أرضي. لديه تمويل جاهز من البنك.',
   activities:[
     {id:'A1',type:'call',title:'اتصال أول تعريفي',date:'2026-05-10',notes:'تم شرح الخدمات'},
     {id:'A2',type:'viewing',title:'معاينة شقة النرجس',propId:'P1',date:'2026-05-18',notes:'أعجبه لكن يريد مقارنة'},
     {id:'A3',type:'call',title:'متابعة بعد المعاينة',date:'2026-06-01',notes:'جاهز للتفاوض'},
   ]},
  {id:'L2',name:'سارة محمد العمري',phone:'0559876543',email:'sara.omari@hotmail.com',
   source:'إعلان إنستغرام',stage:'عرض',status:'دافئ',score:72,
   assignedTo:'U3',branchId:'B1',teamId:'T1',createdAt:'2026-05-12',lastActivity:'2026-06-05',
   req:{budgetMin:2500000,budgetMax:4000000,types:['فيلا','تاون هاوس'],areas:['جدة','النعيم'],bedrooms:[5,6]},
   notes:'تبحث عن فيلا للعائلة بحمام سباحة. مطلعة على السوق.',
   activities:[
     {id:'A4',type:'meeting',title:'اجتماع تحديد المتطلبات',date:'2026-05-13',notes:''},
     {id:'A5',type:'viewing',title:'معاينة فيلا جدة الواجهة البحرية',propId:'P2',date:'2026-05-25',notes:'معجبة جداً'},
   ]},
  {id:'L3',name:'محمد عبدالله الغامدي',phone:'0533333333',email:'m.ghamdi@company.com',
   source:'إحالة من عميل',stage:'تفاوض',status:'ساخن',score:93,
   assignedTo:'U2',branchId:'B2',teamId:'T2',createdAt:'2026-05-14',lastActivity:'2026-06-09',
   req:{budgetMin:1200000,budgetMax:1800000,types:['أرض'],areas:['شمال الرياض','القيروان'],bedrooms:[]},
   notes:'مستثمر عقاري، يريد أرض تجارية للتطوير. لديه شريك.',
   activities:[
     {id:'A6',type:'call',title:'اتصال تعريف بالفرصة',date:'2026-05-14',notes:''},
     {id:'A7',type:'meeting',title:'اجتماع تفصيلي بالمكتب',date:'2026-05-22',notes:''},
     {id:'A8',type:'email',title:'إرسال تفاصيل الأرض',date:'2026-06-01',notes:''},
     {id:'A9',type:'viewing',title:'معاينة ميدانية للأرض',propId:'P4',date:'2026-06-05',notes:''},
   ]},
  {id:'L4',name:'نورة فهد الشهري',phone:'0544444444',email:'noura@mail.com',
   source:'معرض عقاري',stage:'جديد',status:'دافئ',score:51,
   assignedTo:'U3',branchId:'B1',teamId:'T1',createdAt:'2026-05-28',lastActivity:'2026-05-28',
   req:{budgetMin:80000,budgetMax:130000,types:['مكتب'],areas:['الدمام','الخبر'],bedrooms:[]},
   notes:'تبحث عن مكتب للإيجار لشركتها الناشئة.',
   activities:[]},
  {id:'L5',name:'فهد عبدالرحمن الدوسري',phone:'0555555555',email:'fahad.d@gmail.com',
   source:'موقع إلكتروني',stage:'تأهيل',status:'دافئ',score:65,
   assignedTo:'U4',branchId:'B1',teamId:'T1',createdAt:'2026-06-01',lastActivity:'2026-06-07',
   req:{budgetMin:3000,budgetMax:5000,types:['شقة مفروشة'],areas:['الرياض'],bedrooms:[2,3]},
   notes:'يريد شقة مفروشة للإيجار الشهري. موظف ناقل كفالة.',
   activities:[
     {id:'A10',type:'call',title:'اتصال تأهيل',date:'2026-06-01',notes:'تم شرح الخيارات المتاحة'},
   ]},
  {id:'L6',name:'رانيا عمر السالم',phone:'0566666666',email:'rania.s@outlook.com',
   source:'إعلان تويتر',stage:'جديد',status:'ساخن',score:78,
   assignedTo:'U3',branchId:'B1',teamId:'T1',createdAt:'2026-06-06',lastActivity:'2026-06-06',
   req:{budgetMin:600000,budgetMax:900000,types:['شقة','تاون هاوس'],areas:['الرياض','شرق الرياض'],bedrooms:[3,4]},
   notes:'رقم جيد وبدأت بالتفاعل على الموقع. أولوية للمتابعة السريعة.',
   activities:[]},
  {id:'L7',name:'خالد ناصر المطيري',phone:'0577777777',email:'khalid.m@invest.com',
   source:'إحالة من محامٍ',stage:'إغلاق',status:'ساخن',score:95,
   assignedTo:'U2',branchId:'B2',teamId:'T2',createdAt:'2026-04-20',lastActivity:'2026-06-08',
   req:{budgetMin:3000000,budgetMax:5000000,types:['فيلا'],areas:['جدة','حي التيسير'],bedrooms:[5,6,7]},
   notes:'مستثمر ومشتري جاد. تم الاتفاق المبدئي على فيلا جدة.',
   activities:[
     {id:'A11',type:'viewing',title:'معاينة فيلا جدة 2',propId:'P2',date:'2026-05-30',notes:''},
     {id:'A12',type:'meeting',title:'اجتماع تفاوض السعر',date:'2026-06-04',notes:''},
   ]},
  {id:'L8',name:'منى سعد العتيبي',phone:'0588888888',email:'mona@personal.com',
   source:'معرض عقاري',stage:'خسارة',status:'بارد',score:20,
   assignedTo:'U3',branchId:'B1',teamId:'T1',createdAt:'2026-04-10',lastActivity:'2026-05-01',
   req:{budgetMin:500000,budgetMax:700000,types:['شقة'],areas:['الرياض'],bedrooms:[2]},
   notes:'',lostReason:'اشترت من مكتب آخر بسعر أقل',
   activities:[]},
],

// ── CONTACTS ──────────────────────────────────────────────────
contacts: [
  {id:'C1',name:'أحمد خالد العنزي',
   phones:[{label:'جوال',number:'0501234567'},{label:'عمل',number:'0112223333'}],
   emails:[{label:'شخصي',email:'ahmed@gmail.com'},{label:'عمل',email:'ahmed.a@company.sa'}],
   type:'مشتري',company:'',address:'الرياض - حي النرجس',birthday:'1985-03-15',
   tags:['مهتم بشقق','تمويل جاهز'],linkedLeads:['L1'],linkedDeals:['D1'],
   notes:'عميل جيد التعامل. يفضل الرد على واتساب.',source:'موقع إلكتروني',createdAt:'2026-05-10'},
  {id:'C2',name:'سارة محمد العمري',
   phones:[{label:'جوال',number:'0559876543'}],
   emails:[{label:'شخصي',email:'sara.omari@hotmail.com'}],
   type:'مشتري',company:'',address:'جدة - حي الزهراء',birthday:'1990-07-22',
   tags:['فيلا','عائلة كبيرة'],linkedLeads:['L2'],linkedDeals:[],
   notes:'تحب التواصل عبر واتساب. دائماً سريعة الرد.',source:'إعلان',createdAt:'2026-05-12'},
  {id:'C3',name:'محمد عبدالله الغامدي',
   phones:[{label:'جوال',number:'0533333333'},{label:'جوال 2',number:'0544556677'},{label:'مكتب',number:'0134445555'}],
   emails:[{label:'شخصي',email:'m.ghamdi@gmail.com'},{label:'شركة',email:'m.ghamdi@company.com'}],
   type:'مستثمر',company:'شركة الغامدي للتطوير',address:'الرياض - حي العليا',birthday:'1978-11-05',
   tags:['مستثمر','أراضي','تطوير'],linkedLeads:['L3'],linkedDeals:['D2'],
   notes:'مستثمر محترف. يملك عدة عقارات. اهتمامه بالأراضي والتجاري.',source:'إحالة',createdAt:'2026-04-15'},
  {id:'C4',name:'نورة فهد الشهري',
   phones:[{label:'جوال',number:'0544444444'},{label:'منزل',number:'0136667777'}],
   emails:[{label:'شخصي',email:'noura@mail.com'}],
   type:'مستأجر',company:'شركة إبداع للاستشارات',address:'الدمام - حي الشاطئ',birthday:'1992-04-18',
   tags:['مكاتب','إيجار تجاري'],linkedLeads:['L4'],linkedDeals:[],
   notes:'تحتاج مكتب صغير لشركتها الناشئة.',source:'معرض',createdAt:'2026-05-28'},
  {id:'C5',name:'مجموعة المطيري للاستثمار',
   phones:[{label:'مكتب',number:'0126667777'},{label:'مدير عام',number:'0577777777'}],
   emails:[{label:'رسمي',email:'info@almutairi-invest.com'},{label:'مدير',email:'khalid.m@invest.com'}],
   type:'مستثمر',company:'مجموعة المطيري للاستثمار',address:'جدة - حي الحمراء',birthday:'',
   tags:['استثمار','فلل','تجاري','مستثمر VIP'],linkedLeads:['L7'],linkedDeals:['D4'],
   notes:'شركة استثمارية كبيرة. عمليات شراء متعددة سنوياً. علاقة تجارية مهمة.',source:'إحالة',createdAt:'2026-04-20'},
  {id:'C6',name:'فهد عبدالرحمن الدوسري',
   phones:[{label:'جوال',number:'0555555555'}],
   emails:[{label:'شخصي',email:'fahad.d@gmail.com'}],
   type:'مستأجر',company:'',address:'الرياض - حي الروضة',birthday:'1995-09-30',
   tags:['إيجار','مفروش'],linkedLeads:['L5'],linkedDeals:[],
   notes:'يبحث عن شقة مفروشة.',source:'موقع إلكتروني',createdAt:'2026-06-01'},
],

// ── PROPERTIES ────────────────────────────────────────────────
props: [
  {id:'P1',name:'شقة الرياض - 3 غرف مميزة',type:'شقة',
   bedrooms:3,bathrooms:2,parking:1,floor:3,totalFloors:12,area:185,buildingAge:2,
   price:875000,priceType:'بيع',location:'الرياض - حي النرجس',district:'النرجس',city:'الرياض',
   status:'متاح',published:true,publishedPortals:['موقعنا','بيوت','عقار'],
   photos:4,amenities:['مسبح','صالة رياضية','حراسة 24 ساعة','موقف سيارات','مصعد','شرفة','تكييف مركزي'],
   description:'شقة راقية في مجمع سكني متكامل. تشطيبات عالية الجودة. قريبة من المدارس والخدمات.',
   documents:[{name:'الصك العقاري',type:'pdf'},{name:'مخطط الشقة',type:'pdf'},{name:'البروشور',type:'pdf'}],
   priceHistory:[{price:920000,date:'2026-03-01',reason:'سعر البداية'},{price:875000,date:'2026-05-01',reason:'تخفيض تسعيري'}],
   viewings:12,linkedDeals:['D1']},
  {id:'P2',name:'فيلا جدة - الواجهة البحرية الفاخرة',type:'فيلا',
   bedrooms:6,bathrooms:5,parking:3,floor:0,totalFloors:3,area:620,buildingAge:5,
   price:3800000,priceType:'بيع',location:'جدة - حي التيسير',district:'التيسير',city:'جدة',
   status:'متاح',published:true,publishedPortals:['موقعنا','بيوت'],
   photos:12,amenities:['مسبح خاص','حديقة','غرفة خادمة','مجلس رجال','مجلس نساء','مطبخ أمريكي','شرفات واسعة','كاميرات مراقبة'],
   description:'فيلا استثنائية بتشطيبات إيطالية فاخرة. إطلالة بحرية جزئية. موقع راقٍ جداً.',
   documents:[{name:'الصك العقاري',type:'pdf'},{name:'مخطط الفيلا',type:'pdf'},{name:'تقرير الفحص',type:'pdf'},{name:'البروشور الفاخر',type:'pdf'}],
   priceHistory:[{price:4200000,date:'2026-01-15',reason:'سعر البداية'},{price:3800000,date:'2026-04-20',reason:'مراجعة تنافسية'}],
   viewings:28,linkedDeals:['D2','D4']},
  {id:'P3',name:'مكتب دمام - الشاطئ التجاري',type:'مكتب',
   bedrooms:0,bathrooms:2,parking:2,floor:5,totalFloors:10,area:95,buildingAge:8,
   price:130000,priceType:'إيجار سنوي',location:'الدمام - حي الشاطئ',district:'الشاطئ',city:'الدمام',
   status:'محجوز',published:false,publishedPortals:[],
   photos:3,amenities:['استقبال مشترك','قاعة اجتماعات','إنترنت فايبر','مولد كهربائي'],
   description:'مكتب تجاري متميز في برج حديث. مناسب للشركات الصغيرة والمتوسطة.',
   documents:[{name:'عقد الإيجار',type:'pdf'}],
   priceHistory:[{price:130000,date:'2026-02-01',reason:'سعر البداية'}],
   viewings:6,linkedDeals:['D3']},
  {id:'P4',name:'أرض تجارية - شمال الرياض',type:'أرض',
   bedrooms:0,bathrooms:0,parking:0,floor:0,totalFloors:0,area:800,buildingAge:0,
   price:1650000,priceType:'بيع',location:'الرياض - القيروان',district:'القيروان',city:'الرياض',
   status:'متاح',published:true,publishedPortals:['موقعنا','عقار'],
   photos:3,amenities:['شارع 30م','زاوية','تجاري سكني','خدمات متكاملة'],
   description:'أرض زاوية على شارعين. مخطط نظامي تجاري سكني. خدمات ممتدة.',
   documents:[{name:'الصك',type:'pdf'},{name:'المخطط التنظيمي',type:'pdf'}],
   priceHistory:[{price:1800000,date:'2026-02-10',reason:'سعر البداية'},{price:1650000,date:'2026-05-05',reason:'مراجعة'}],
   viewings:9,linkedDeals:['D2']},
  {id:'P5',name:'شقة مفروشة - الرياض المميزة',type:'شقة مفروشة',
   bedrooms:2,bathrooms:2,parking:1,floor:4,totalFloors:8,area:120,buildingAge:3,
   price:4500,priceType:'إيجار شهري',location:'الرياض - حي الروضة',district:'الروضة',city:'الرياض',
   status:'متاح',published:true,publishedPortals:['موقعنا','بيوت','إيجار'],
   photos:6,amenities:['مفروش بالكامل','أجهزة كهربائية','واي فاي','مجلس','غرفة طعام','موقف'],
   description:'شقة مفروشة بالكامل بأثاث عصري. جاهزة للسكن فوراً.',
   documents:[{name:'عقد إيجار',type:'pdf'}],
   priceHistory:[{price:4500,date:'2026-04-01',reason:'سعر البداية'}],
   viewings:15,linkedDeals:[]},
  {id:'P6',name:'تاون هاوس جدة - مجمع الأمواج',type:'تاون هاوس',
   bedrooms:4,bathrooms:3,parking:2,floor:0,totalFloors:3,area:290,buildingAge:1,
   price:1950000,priceType:'بيع',location:'جدة - حي الشاطئ',district:'الشاطئ',city:'جدة',
   status:'مباع',published:false,publishedPortals:[],
   photos:8,amenities:['روف تيراس','مسبح مشترك','أمن وحراسة','نادي رياضي','مطبخ مفتوح'],
   description:'تاون هاوس فاخر في مجمع متكامل على الكورنيش مباشرة.',
   documents:[{name:'عقد البيع',type:'pdf'},{name:'الصك المحول',type:'pdf'}],
   priceHistory:[{price:2100000,date:'2025-12-01',reason:'سعر البداية'},{price:1950000,date:'2026-02-15',reason:'بيع'}],
   viewings:19,linkedDeals:['D5']},
],

// ── DEALS ────────────────────────────────────────────────────
deals: [
  {id:'D1',name:'صفقة شقة النرجس - أحمد',leadId:'L1',contactId:'C1',propId:'P1',
   stage:'عرض',value:875000,commission:2.5,
   commissionSplit:{agent:40,office:50,referral:10},
   branchId:'B1',assignedTo:'U3',teamId:'T1',
   expectedCloseDate:'2026-07-15',createdAt:'2026-05-18',
   stageHistory:[
     {stage:'تواصل أولي',date:'2026-05-18',user:'محمد الفيصل'},
     {stage:'تأهيل',date:'2026-05-20',user:'سلمى الحربي'},
     {stage:'عرض',date:'2026-06-01',user:'سلمى الحربي'},
   ],
   documents:[{name:'عرض السعر',type:'pdf'},{name:'التقرير التقييمي',type:'pdf'}],
   notes:'العميل جاهز التمويلي. ينتظر موافقة الشريك.'},
  {id:'D2',name:'صفقة أرض القيروان - الغامدي',leadId:'L3',contactId:'C3',propId:'P4',
   stage:'تفاوض',value:1650000,commission:2,
   commissionSplit:{agent:45,office:45,referral:10},
   branchId:'B2',assignedTo:'U2',teamId:'T2',
   expectedCloseDate:'2026-07-01',createdAt:'2026-05-22',
   stageHistory:[
     {stage:'تواصل أولي',date:'2026-05-22',user:'علي العمري'},
     {stage:'تأهيل',date:'2026-05-28',user:'علي العمري'},
     {stage:'عرض',date:'2026-06-05',user:'علي العمري'},
     {stage:'تفاوض',date:'2026-06-08',user:'علي العمري'},
   ],
   documents:[{name:'تقرير تقييم الأرض',type:'pdf'},{name:'مسودة العقد',type:'pdf'},{name:'مخطط الأرض',type:'pdf'}],
   notes:''},
  {id:'D3',name:'صفقة مكتب الدمام - نورة',leadId:'L4',contactId:'C4',propId:'P3',
   stage:'توقيع عقد',value:130000,commission:3,
   commissionSplit:{agent:50,office:50,referral:0},
   branchId:'B1',assignedTo:'U3',teamId:'T1',
   expectedCloseDate:'2026-06-20',createdAt:'2026-05-30',
   stageHistory:[
     {stage:'تواصل أولي',date:'2026-05-30',user:'سلمى الحربي'},
     {stage:'تأهيل',date:'2026-06-01',user:'سلمى الحربي'},
     {stage:'عرض',date:'2026-06-03',user:'سلمى الحربي'},
     {stage:'تفاوض',date:'2026-06-06',user:'سلمى الحربي'},
     {stage:'توقيع عقد',date:'2026-06-08',user:'سلمى الحربي'},
   ],
   documents:[{name:'عقد الإيجار',type:'pdf'},{name:'الوثائق الرسمية',type:'pdf'}],
   notes:'جارٍ إتمام إجراءات التوثيق.'},
  {id:'D4',name:'صفقة فيلا جدة - مجموعة المطيري',leadId:'L7',contactId:'C5',propId:'P2',
   stage:'تأهيل',value:3800000,commission:2,
   commissionSplit:{agent:35,office:55,referral:10},
   branchId:'B2',assignedTo:'U2',teamId:'T2',
   expectedCloseDate:'2026-08-30',createdAt:'2026-06-04',
   stageHistory:[
     {stage:'تواصل أولي',date:'2026-06-04',user:'علي العمري'},
     {stage:'تأهيل',date:'2026-06-07',user:'علي العمري'},
   ],
   documents:[],
   notes:'صفقة VIP. تحتاج موافقة مجلس الإدارة.'},
  {id:'D5',name:'صفقة تاون هاوس جدة - مكتملة',leadId:'',contactId:'',propId:'P6',
   stage:'مكتمل',value:1950000,commission:2.5,
   commissionSplit:{agent:40,office:50,referral:10},
   branchId:'B2',assignedTo:'U2',teamId:'T2',
   expectedCloseDate:'2026-03-01',createdAt:'2026-01-15',
   stageHistory:[
     {stage:'مكتمل',date:'2026-03-01',user:'علي العمري'},
   ],
   documents:[{name:'عقد البيع الموثق',type:'pdf'}],
   notes:'صفقة مكتملة ومحولة.'},
],

// ── ACTIVITIES ────────────────────────────────────────────────
activities: [
  {id:'ACT1',type:'call',title:'اتصال متابعة مع أحمد العنزي',leadId:'L1',contactId:'C1',dealId:'D1',propId:'',date:'2026-06-09',time:'10:00',duration:15,status:'متأخر',assignedTo:'U3',notes:''},
  {id:'ACT2',type:'viewing',title:'معاينة فيلا جدة - سارة العمري',leadId:'L2',contactId:'C2',dealId:'',propId:'P2',date:'2026-06-09',time:'15:30',duration:60,status:'اليوم',assignedTo:'U2',notes:''},
  {id:'ACT3',type:'task',title:'إرسال عقد مكتب الدمام للتوقيع',leadId:'L4',contactId:'C4',dealId:'D3',propId:'P3',date:'2026-06-10',time:'09:00',duration:0,status:'قادم',assignedTo:'U3',notes:''},
  {id:'ACT4',type:'call',title:'اتصال تمهيد مع محمد الغامدي',leadId:'L3',contactId:'C3',dealId:'D2',propId:'',date:'2026-06-10',time:'11:30',duration:20,status:'قادم',assignedTo:'U2',notes:''},
  {id:'ACT5',type:'meeting',title:'اجتماع مجموعة المطيري بالمكتب',leadId:'L7',contactId:'C5',dealId:'D4',propId:'',date:'2026-06-11',time:'14:00',duration:90,status:'قادم',assignedTo:'U1',notes:'اجتماع مهم - ضرورة حضور المدير'},
  {id:'ACT6',type:'email',title:'إرسال قائمة عقارات الأرض لرانيا',leadId:'L6',contactId:'',dealId:'',propId:'',date:'2026-06-09',time:'09:00',duration:0,status:'اليوم',assignedTo:'U3',notes:''},
  {id:'ACT7',type:'task',title:'تحديث صور شقة النرجس',leadId:'',contactId:'',dealId:'',propId:'P1',date:'2026-06-11',time:'',duration:0,status:'قادم',assignedTo:'U3',notes:''},
  {id:'ACT8',type:'call',title:'متابعة فهد الدوسري',leadId:'L5',contactId:'C6',dealId:'',propId:'',date:'2026-06-08',time:'16:00',duration:10,status:'متأخر',assignedTo:'U4',notes:''},
  {id:'ACT9',type:'viewing',title:'معاينة شقة النرجس - ثانية',leadId:'L1',contactId:'C1',dealId:'D1',propId:'P1',date:'2026-06-07',time:'11:00',duration:45,status:'مكتمل',assignedTo:'U3',notes:'سارت بشكل ممتاز'},
  {id:'ACT10',type:'note',title:'ملاحظة: سارة تفضل التواصل الصباحي',leadId:'L2',contactId:'C2',dealId:'',propId:'',date:'2026-06-06',time:'',duration:0,status:'مكتمل',assignedTo:'U3',notes:'أبلغتنا أنها متاحة فقط بين 9 و12 ص'},
],

// ── CONVERSATIONS (WhatsApp Inbox) ────────────────────────────
conversations: [
  {id:'CV1',contactId:'C1',contactName:'أحمد خالد العنزي',contactPhone:'0501234567',
   lastMsg:'متى يمكن المعاينة الثانية؟',lastTime:'09:47',unread:2,status:'online'},
  {id:'CV2',contactId:'C3',contactName:'محمد الغامدي',contactPhone:'0533333333',
   lastMsg:'أرسل لي تقرير تقييم الأرض',lastTime:'أمس',unread:0,status:'offline'},
  {id:'CV3',contactId:'C5',contactName:'مجموعة المطيري',contactPhone:'0577777777',
   lastMsg:'سيتصل بك مدير التطوير خلال ساعة',lastTime:'أمس',unread:1,status:'offline'},
  {id:'CV4',contactId:'C2',contactName:'سارة العمري',contactPhone:'0559876543',
   lastMsg:'شكراً جزيلاً على المتابعة 🌹',lastTime:'الثلاثاء',unread:0,status:'offline'},
],
messages: {
  CV1:[
    {id:'m1',dir:'in',type:'text',text:'السلام عليكم، أنا أحمد خالد. تواصلت معكم بخصوص الشقة في النرجس.',time:'09:30',status:'read'},
    {id:'m2',dir:'out',type:'text',text:'وعليكم السلام! أهلاً وسهلاً يا أحمد. نعم الشقة متاحة ونسعد بخدمتك.',time:'09:32',status:'read'},
    {id:'m3',dir:'in',type:'image',text:'هذا صورة من موقع مشابه أحبه',mediaName:'مثال_مطبخ.jpg',mediaSize:'1.8 MB',time:'09:35',status:'read'},
    {id:'m4',dir:'out',type:'text',text:'جميل! الشقة في النرجس بها مطبخ مفتوح بنفس الأسلوب. هل تريد موعد معاينة؟',time:'09:38',status:'read'},
    {id:'m5',dir:'in',type:'voice',duration:'0:28',time:'09:40',status:'read'},
    {id:'m6',dir:'out',type:'template',templateName:'موعد معاينة',text:'مرحباً أحمد 👋\nتم تحديد موعد معاينتك:\n📅 التاريخ: السبت 14 يونيو 2026\n🕙 الوقت: 10:00 صباحاً\n📍 الموقع: حي النرجس\n\nللتأكيد أو إعادة الجدولة تواصل معنا.',time:'09:42',status:'delivered'},
    {id:'m7',dir:'in',type:'document',text:'',mediaName:'متطلبات_العميل.pdf',mediaSize:'234 KB',time:'09:45',status:'read'},
    {id:'m8',dir:'in',type:'text',text:'متى يمكن المعاينة الثانية؟',time:'09:47',status:'read'},
  ],
  CV2:[
    {id:'m1',dir:'out',type:'text',text:'صباح الخير محمد، تفضل تقرير التقييم.',time:'أمس 08:30',status:'read'},
    {id:'m2',dir:'out',type:'document',text:'',mediaName:'تقرير_تقييم_الأرض_Q2026.pdf',mediaSize:'1.2 MB',time:'أمس 08:31',status:'read'},
    {id:'m3',dir:'in',type:'text',text:'شكراً. السعر مناسب لكن أحتاج مشاورة شريكي.',time:'أمس 10:15',status:'read'},
    {id:'m4',dir:'in',type:'location',text:'موقع الأرض اللي شفناها مع المساح',time:'أمس 10:16',status:'read'},
    {id:'m5',dir:'in',type:'text',text:'أرسل لي تقرير تقييم الأرض',time:'أمس 14:22',status:'read'},
  ],
  CV3:[
    {id:'m1',dir:'out',type:'template',templateName:'مقدمة العرض',text:'مرحباً مجموعة المطيري الكريمة 🏢\nيسعدنا تقديم عرضنا الحصري لفيلا جدة الفاخرة.\nالسعر المميز: 3,800,000 ر.س\n\nتشمل الصفقة: الصك، تقرير الفحص، وضمان سنة.',time:'الأحد 14:00',status:'read'},
    {id:'m2',dir:'in',type:'text',text:'وصلنا العرض. سيتصل بك مدير التطوير خلال ساعة',time:'الأحد 15:30',status:'read'},
    {id:'m3',dir:'in',type:'voice',duration:'1:12',time:'الأحد 16:05',status:'read'},
    {id:'m4',dir:'out',type:'text',text:'سيتصل بك مدير التطوير خلال ساعة',time:'أمس 09:00',status:'delivered'},
  ],
  CV4:[
    {id:'m1',dir:'out',type:'text',text:'صباح الخير سارة، كيف حال معاينة الفيلا؟',time:'الثلاثاء 09:00',status:'read'},
    {id:'m2',dir:'in',type:'text',text:'الحمد لله. الفيلا رائعة جداً. أنا مهتمة جداً!',time:'الثلاثاء 09:15',status:'read'},
    {id:'m3',dir:'out',type:'text',text:'ممتاز! هل تريدين جدولة اجتماع للتفاوض على السعر؟',time:'الثلاثاء 09:17',status:'read'},
    {id:'m4',dir:'in',type:'text',text:'شكراً جزيلاً على المتابعة 🌹',time:'الثلاثاء 10:30',status:'read'},
  ],
},
CUR_CONV: 'CV1',

// ── BRANCHES ─────────────────────────────────────────────────
branches: [
  {id:'B1',name:'فرع الرياض الرئيسي',manager:'U1',phone:'0112223344',address:'الرياض - حي العليا، شارع العروبة',agents:3,leads:6,deals:3,revenue:1200000,active:true},
  {id:'B2',name:'فرع جدة',manager:'U2',phone:'0126667788',address:'جدة - حي الحمراء، طريق الملك فهد',agents:2,leads:2,deals:3,revenue:5600000,active:true},
],

// ── TEAMS ────────────────────────────────────────────────────
teams: [
  {id:'T1',name:'فريق الرياض أ',branchId:'B1',leader:'U3',members:['U3','U4'],target:3000000},
  {id:'T2',name:'فريق جدة',branchId:'B2',leader:'U2',members:['U2'],target:6000000},
],

// ── USERS ────────────────────────────────────────────────────
users: [
  {id:'U1',name:'محمد خالد الفيصل',email:'mohammed@est8.com',phone:'0501111111',role:'owner',branch:'B1',team:'',status:'نشط',avatar:'م',joinDate:'2024-01-01',deals:0,leads:0,revenue:0},
  {id:'U2',name:'علي عمر العمري',email:'ali@est8.com',phone:'0502222222',role:'branch_manager',branch:'B2',team:'T2',status:'نشط',avatar:'ع',joinDate:'2024-03-15',deals:3,leads:2,revenue:5600000},
  {id:'U3',name:'سلمى أحمد الحربي',email:'salma@est8.com',phone:'0503333333',role:'sales_agent',branch:'B1',team:'T1',status:'نشط',avatar:'س',joinDate:'2024-06-01',deals:2,leads:5,revenue:1005000},
  {id:'U4',name:'عمر سعد القحطاني',email:'omar@est8.com',phone:'0504444444',role:'team_leader',branch:'B1',team:'T1',status:'نشط',avatar:'ع',joinDate:'2025-01-10',deals:0,leads:1,revenue:0},
],

// ── TARGETS ──────────────────────────────────────────────────
targets: [
  {id:'TG1',scope:'agent',scopeId:'U3',period:'monthly',year:2026,month:6,
   metrics:[{type:'leads',target:12,achieved:5},{type:'deals',target:3,achieved:2},{type:'revenue',target:1500000,achieved:1005000},{type:'viewings',target:20,achieved:14}]},
  {id:'TG2',scope:'agent',scopeId:'U2',period:'monthly',year:2026,month:6,
   metrics:[{type:'leads',target:8,achieved:2},{type:'deals',target:2,achieved:3},{type:'revenue',target:3000000,achieved:5600000},{type:'viewings',target:15,achieved:28}]},
  {id:'TG3',scope:'agent',scopeId:'U4',period:'monthly',year:2026,month:6,
   metrics:[{type:'leads',target:10,achieved:1},{type:'deals',target:2,achieved:0},{type:'revenue',target:1000000,achieved:0},{type:'viewings',target:12,achieved:3}]},
  {id:'TG4',scope:'branch',scopeId:'B1',period:'monthly',year:2026,month:6,
   metrics:[{type:'leads',target:25,achieved:6},{type:'deals',target:6,achieved:2},{type:'revenue',target:3000000,achieved:1200000},{type:'viewings',target:40,achieved:18}]},
  {id:'TG5',scope:'branch',scopeId:'B2',period:'monthly',year:2026,month:6,
   metrics:[{type:'leads',target:20,achieved:2},{type:'deals',target:4,achieved:3},{type:'revenue',target:5000000,achieved:5600000},{type:'viewings',target:30,achieved:28}]},
],

// ── NOTIFICATIONS ─────────────────────────────────────────────
notifs: [
  {id:'N1',title:'عميل جديد متميز',body:'أحمد خالد العنزي — score 88 — مهتم بشقة النرجس',type:'lead',time:'منذ 35 دقيقة',read:false},
  {id:'N2',title:'تذكير: معاينة اليوم',body:'معاينة فيلا جدة مع سارة العمري الساعة 3:30 م',type:'activity',time:'منذ ساعة',read:false},
  {id:'N3',title:'صفقة تقدمت للتوقيع',body:'مكتب الدمام - نورة الشهري → توقيع عقد',type:'deal',time:'منذ 3 ساعات',read:false},
  {id:'N4',title:'رسالة واتساب',body:'محمد الغامدي: أرسل لي تقرير تقييم الأرض',type:'msg',time:'أمس 14:22',read:true},
  {id:'N5',title:'عميل محتمل فقدناه',body:'منى العتيبي — اشترت من مكتب منافس',type:'loss',time:'منذ أسبوع',read:true},
  {id:'N6',title:'تجديد اشتراك قادم',body:'الاشتراك ينتهي خلال 21 يوماً — تجديد مطلوب',type:'billing',time:'منذ يومين',read:true},
],

// ── BILLING ──────────────────────────────────────────────────
billing: {
  plan:'pro',renewal:'2026-09-01',
  users:{used:4,limit:10},leads:{used:8,limit:200},storage:{used:2.1,limit:20},
  whatsapp:{used:142,limit:1000},
  invoices:[
    {id:'INV-2026-06',date:'2026-06-01',amount:899,status:'مدفوع'},
    {id:'INV-2026-05',date:'2026-05-01',amount:899,status:'مدفوع'},
    {id:'INV-2026-04',date:'2026-04-01',amount:899,status:'مدفوع'},
  ]
},

};
